<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFvMHqHu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFvMHqHu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFvMHqHu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFvMHqHu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFvMHqHu\App_KernelDevDebugContainer([
    'container.build_hash' => 'FvMHqHu',
    'container.build_id' => 'bb60497d',
    'container.build_time' => 1680097302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFvMHqHu');
